---
dataset:
  path : '/home/rupadhyay/ir_datasets/amazon_KDD_q_p_ranking/'
  collection : 'product_catalogue-v0.2.csv'
  train : 'train-v0.2.csv'
  test : 'test_public-v0.2.csv'
  seed : 42
  train_split_rate : 60
  index_each_data: False
  create_submission_file: True
  evaluate_train: False